### PR TITLE
Explicitly specify Soup parser per warning

### PR DESCRIPTION
**Pull request by stkent**

### CODE REVIEW

**Comment by macklinu** [comment]
:+1:

**Comment by stkent** [comment]
LGTM?

**Comment by macklinu** [comment]
I think so. I haven't had time to pull these down and test things yet this week, so feel free to merge PRs if you're blocked. I'll do my best to look at things during the day, but will probably take further looks in the evenings / later in the week.

**Comment by stkent** [comment]
:+1: I will leave open and work on some other things :)

**Comment by macklinu** [comment]
Ah yes, I see the warning now:

```
/Library/Python/2.7/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
```

:white_check_mark:

**Pull request merged**
